#!/bin/sh 

/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=4 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=687 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2154 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=16 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=139 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=89 --schedule_time=6  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=115 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=127 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=504 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=734 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1094 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1260 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1534 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=41 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=39 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=7 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=85 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=847 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=179 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1476 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=378 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=417 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=47 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=17 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=319 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=461 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1095 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=32 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=138 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=140 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=279 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=128 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=27 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=211 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=135 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=508 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1527 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=119 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=43 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=517 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=343 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1930 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3302 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2168 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=50 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1925 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=33 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1605 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=130 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2327 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2853 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=463 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1673 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1583 --schedule_time=7  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=11 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=20 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=14 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=516 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=384 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2453 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=15 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=18 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=145 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=336 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=440 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=955 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1715 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1817 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2014 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3266 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3297 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=10 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=224 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=316 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=44 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=719 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2129 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1062 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1223 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1493 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1935 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2841 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=107 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=386 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=129 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=740 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1448 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1399 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1608 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1908 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2389 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=524 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=544 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1295 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3270 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3336 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=403 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=506 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=941 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1394 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1606 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1957 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2229 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2382 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2449 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2516 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3317 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=36 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=186 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=249 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=275 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=393 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=327 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1096 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=220 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1550 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1913 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=81 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=259 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=163 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=464 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=825 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1862 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2146 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3271 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=460 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=100 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1609 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2991 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3321 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2703 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2927 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1750 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2963 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3231 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=99 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=548 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=699 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=950 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1974 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2865 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3264 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3286 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3308 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=143 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=395 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=575 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1567 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2807 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=265 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3243 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2657 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=171 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2002 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2686 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2896 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3138 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3265 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3289 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3334 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=19 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=800 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=922 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2358 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2946 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3338 --schedule_time=8  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=822 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=42 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1967 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=396 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=771 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=884 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1100 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1303 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=82 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=349 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=577 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=268 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=202 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1106 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=34 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=283 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=591 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1778 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=195 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=51 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=520 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=83 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=362 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2429 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2628 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=383 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1384 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=62 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=158 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=494 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=942 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1396 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1892 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2179 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2250 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2388 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2587 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2857 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3247 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3279 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3307 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=170 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=435 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=468 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=670 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2155 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2170 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2326 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2420 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2489 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3167 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3313 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3335 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=148 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=144 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=496 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=281 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=455 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=807 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1387 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1874 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2151 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2156 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2197 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2369 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2821 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2512 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3277 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3301 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3316 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3341 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=49 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=248 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=624 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1288 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1547 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1814 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2167 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2163 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2267 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2479 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3013 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3333 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=131 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=209 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=370 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=399 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=178 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=799 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1032 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1341 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1484 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1720 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1835 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1928 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2035 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2160 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2495 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2931 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3202 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3299 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3314 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=63 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=227 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=103 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=352 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=106 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=727 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1091 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1224 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1877 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2153 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2159 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2970 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3284 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=181 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=429 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=625 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=655 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=876 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1219 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1468 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1816 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2169 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2165 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2158 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2399 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2485 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3312 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=104 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=236 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=578 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=645 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=706 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2500 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=1691 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2092 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2166 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2192 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2501 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2837 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=2391 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3300 --schedule_time=9  &  
/usr/bin/php /home/srv/www/htdocs/reelmediad_v2/protected/yiic dailymail generate --argv=3315 --schedule_time=9  &  
